### ISSUE TITLE
addSubscriber method issue since 0.2.2 release

### ISSUE THREAD

**Issue by juban** [fkooman/guzzle-bearer-auth-plugin#6]
Since 0.2.2 release, with the following code:

```php
use Guzzle\Http\Client;
use fkooman\Guzzle\Plugin\BearerAuth\BearerAuth;

...

$client = new Client();
$bearerAuth = new BearerAuth($this->_authKey);
$client->addSubscriber($bearerAuth);
```
I get the following Exception:

`Argument 1 passed to Guzzle\Common\AbstractHasDispatcher::addSubscriber() must implement interface Symfony\Component\EventDispatcher\EventSubscriberInterface, instance of fkooman\Guzzle\Plugin\BearerAuth\BearerAuth given`

Works fine with 0.2.1 release.

I can't figure out what's wrong.

**Comment by juban** [comment]
OK, obviously, it's a Guzzle dependency issue. Sticking with 0.2.1 version. 
You should change the tag of the current version to something like 0.3.x because it's a major update ;)

**Comment by fkooman** [comment]
I personally don't use this software any more. I am using my REST framework with built in Bearer support (https://github.com/fkooman/php-lib-rest-plugin-bearer).

I also still need to support PHP 5.3 with my apps, so I cannot use the latest version of Guzzle unfortunately ;(
